### ISSUE TITLE
Rain is only tracked once

### ISSUE THREAD

**Issue by Jviguy** [Jviguy/WaterBucket#1]
After the first initial 28 minutes, the program is meant to start collecting again automatically, but the current version fails to do accomplish this.

**Comment by Jviguy** [comment]
This should be resolved by [02559d8](https://github.com/Jviguy/WaterBucket/commit/02559d860ab219097a01b46f0737969bf77a0161), but this still needs testing.

**Comment by Jviguy** [comment]
Resolved by v0.3.0.

**Comment by ZodiacX2** [comment]
hey can you hel p me do you have free battle hcaptcha solver script for rustclash?
